name: deploy_frontend
#deploys when push is made from frontend folder

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: azure/login
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azuremyresumestorage --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azuremyresume" --name "azuremyresume" --resource-group "azureresume-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()